name = "Modus Operandi"

[colors]
background = "#ffffff"
foreground = "#000000"
cursor = "#000000"
selection_background = "#bdbdbd"
selection_foreground = "#000000"

[colors.ansi]
black = "#000000"
red = "#a60000"
green = "#006800"
yellow = "#6f5500"
blue = "#0031a9"
magenta = "#721045"
cyan = "#005e8b"
white = "#a6a6a6"
bright_black = "#595959"
bright_red = "#972500"
bright_green = "#00663f"
bright_yellow = "#884900"
bright_blue = "#3548cf"
bright_magenta = "#531ab6"
bright_cyan = "#005f5f"
bright_white = "#595959"
