name = "Tokyo Night Storm"

[colors]
background = "#24283b"
foreground = "#a9b1d6"
cursor = "#c0caf5"
selection_background = "#2e3c64"
selection_foreground = "#c0caf5"

[colors.ansi]
black = "#1d202f"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#414868"
bright_red = "#f7768e"
bright_green = "#9ece6a"
bright_yellow = "#e0af68"
bright_blue = "#7aa2f7"
bright_magenta = "#bb9af7"
bright_cyan = "#7dcfff"
bright_white = "#c0caf5"
