name = "Dayfox"

[colors]
background = "#f6f2ee"
foreground = "#3d2b5a"
cursor = "#3d2b5a"
selection_background = "#e7d2be"
selection_foreground = "#3d2b5a"

[colors.ansi]
black = "#352c24"
red = "#a5222f"
green = "#396847"
yellow = "#ac5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
white = "#f2e9e1"
bright_black = "#534c45"
bright_red = "#b3434e"
bright_green = "#577f63"
bright_yellow = "#b86e28"
bright_blue = "#4863b6"
bright_magenta = "#8452d5"
bright_cyan = "#488d93"
bright_white = "#f4ece6"
