name = "Oxocarbon Light"

[colors]
background = "#d0d0d0"
foreground = "#161616"
cursor = "#373737"
selection_background = "#0f62fe"
selection_foreground = "#f2f2f2"

[colors.ansi]
black = "#525252"
red = "#ee5396"
green = "#42be65"
yellow = "#ffab91"
blue = "#0f62fe"
magenta = "#be95ff"
cyan = "#08bdba"
white = "#ffffff"
bright_black = "#161616"
bright_red = "#ff7eb6"
bright_green = "#42be65"
bright_yellow = "#ffab91"
bright_blue = "#0f62fe"
bright_magenta = "#673ab7"
bright_cyan = "#08bdba"
bright_white = "#d0d0d0"
