use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::ThemeError;
use crate::{AnsiColors, Color, parse_hex_color};

/// Whether a theme targets a dark or light background.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Variant {
    Dark,
    Light,
}

/// Authored theme definition — maps a theme to its provider-specific names.
///
/// Parsed from `themes/<family>/<slug>.toml`:
/// ```text
/// name = "Gruvbox Dark"
/// variant = "dark"
///
/// [providers]
/// kitty = "Gruvbox Dark"
/// wezterm = "Gruvbox Dark (Gogh)"
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThemeDefinition {
    pub name: String,
    pub variant: Variant,
    /// Derived from filename, not serialized in the TOML.
    #[serde(skip)]
    pub slug: String,
    /// Maps provider slug → provider-specific theme name.
    pub providers: HashMap<String, String>,
}

/// Generated per-provider color data for a theme.
///
/// Parsed from `themes/<family>/<slug>.<provider>.toml`:
/// ```text
/// # AUTO-GENERATED by litmus extract-colors — do not edit
/// provider = "kitty"
/// source_version = "0.37.0"
///
/// [colors]
/// background = "#282828"
/// foreground = "#ebdbb2"
/// cursor = "#ebdbb2"
/// selection_background = "#ebdbb2"
/// selection_foreground = "#282828"
///
/// [colors.ansi]
/// black = "#282828"
/// red = "#cc241d"
/// # ...
/// ```
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ProviderColors {
    pub provider: String,
    pub source_version: String,
    pub background: Color,
    pub foreground: Color,
    pub cursor: Color,
    pub selection_background: Color,
    pub selection_foreground: Color,
    pub ansi: AnsiColors,
}

impl ProviderColors {
    /// Create `ProviderColors` from a parsed `Theme` with provider metadata.
    pub fn from_theme(theme: &crate::Theme, provider: &str, source_version: &str) -> Self {
        Self {
            provider: provider.to_string(),
            source_version: source_version.to_string(),
            background: theme.background.clone(),
            foreground: theme.foreground.clone(),
            cursor: theme.cursor.clone(),
            selection_background: theme.selection_background.clone(),
            selection_foreground: theme.selection_foreground.clone(),
            ansi: theme.ansi.clone(),
        }
    }

    /// Serialize to the generated TOML format for writing to disk.
    pub fn to_toml(&self) -> String {
        let a = &self.ansi;
        format!(
            "# AUTO-GENERATED by litmus extract-colors — do not edit\n\
             provider = \"{provider}\"\n\
             source_version = \"{version}\"\n\
             \n\
             [colors]\n\
             background = \"{bg}\"\n\
             foreground = \"{fg}\"\n\
             cursor = \"{cursor}\"\n\
             selection_background = \"{sel_bg}\"\n\
             selection_foreground = \"{sel_fg}\"\n\
             \n\
             [colors.ansi]\n\
             black = \"{black}\"\n\
             red = \"{red}\"\n\
             green = \"{green}\"\n\
             yellow = \"{yellow}\"\n\
             blue = \"{blue}\"\n\
             magenta = \"{magenta}\"\n\
             cyan = \"{cyan}\"\n\
             white = \"{white}\"\n\
             bright_black = \"{bright_black}\"\n\
             bright_red = \"{bright_red}\"\n\
             bright_green = \"{bright_green}\"\n\
             bright_yellow = \"{bright_yellow}\"\n\
             bright_blue = \"{bright_blue}\"\n\
             bright_magenta = \"{bright_magenta}\"\n\
             bright_cyan = \"{bright_cyan}\"\n\
             bright_white = \"{bright_white}\"\n",
            provider = self.provider,
            version = self.source_version,
            bg = self.background.to_hex(),
            fg = self.foreground.to_hex(),
            cursor = self.cursor.to_hex(),
            sel_bg = self.selection_background.to_hex(),
            sel_fg = self.selection_foreground.to_hex(),
            black = a.black.to_hex(),
            red = a.red.to_hex(),
            green = a.green.to_hex(),
            yellow = a.yellow.to_hex(),
            blue = a.blue.to_hex(),
            magenta = a.magenta.to_hex(),
            cyan = a.cyan.to_hex(),
            white = a.white.to_hex(),
            bright_black = a.bright_black.to_hex(),
            bright_red = a.bright_red.to_hex(),
            bright_green = a.bright_green.to_hex(),
            bright_yellow = a.bright_yellow.to_hex(),
            bright_blue = a.bright_blue.to_hex(),
            bright_magenta = a.bright_magenta.to_hex(),
            bright_cyan = a.bright_cyan.to_hex(),
            bright_white = a.bright_white.to_hex(),
        )
    }
}

// -- Raw serde structs for TOML deserialization --

#[derive(Debug, Deserialize)]
struct ProviderColorsRaw {
    provider: String,
    source_version: String,
    colors: ProviderColorsColorsRaw,
}

#[derive(Debug, Deserialize)]
struct ProviderColorsColorsRaw {
    background: String,
    foreground: String,
    cursor: String,
    selection_background: String,
    selection_foreground: String,
    ansi: ProviderAnsiRaw,
}

#[derive(Debug, Deserialize)]
struct ProviderAnsiRaw {
    black: String,
    red: String,
    green: String,
    yellow: String,
    blue: String,
    magenta: String,
    cyan: String,
    white: String,
    bright_black: String,
    bright_red: String,
    bright_green: String,
    bright_yellow: String,
    bright_blue: String,
    bright_magenta: String,
    bright_cyan: String,
    bright_white: String,
}

/// Parse a `ThemeDefinition` from TOML content. The `slug` field is set from `slug_str`.
pub fn parse_theme_definition(input: &str, slug: &str) -> Result<ThemeDefinition, ThemeError> {
    let mut def: ThemeDefinition = toml::from_str(input)?;
    def.slug = slug.to_string();
    Ok(def)
}

/// Parse `ProviderColors` from a generated per-provider TOML file.
pub fn parse_provider_colors(input: &str) -> Result<ProviderColors, ThemeError> {
    let raw: ProviderColorsRaw = toml::from_str(input)?;
    let c = &raw.colors;
    let a = &c.ansi;

    Ok(ProviderColors {
        provider: raw.provider,
        source_version: raw.source_version,
        background: parse_hex_color("background", &c.background)?,
        foreground: parse_hex_color("foreground", &c.foreground)?,
        cursor: parse_hex_color("cursor", &c.cursor)?,
        selection_background: parse_hex_color("selection_background", &c.selection_background)?,
        selection_foreground: parse_hex_color("selection_foreground", &c.selection_foreground)?,
        ansi: AnsiColors {
            black: parse_hex_color("black", &a.black)?,
            red: parse_hex_color("red", &a.red)?,
            green: parse_hex_color("green", &a.green)?,
            yellow: parse_hex_color("yellow", &a.yellow)?,
            blue: parse_hex_color("blue", &a.blue)?,
            magenta: parse_hex_color("magenta", &a.magenta)?,
            cyan: parse_hex_color("cyan", &a.cyan)?,
            white: parse_hex_color("white", &a.white)?,
            bright_black: parse_hex_color("bright_black", &a.bright_black)?,
            bright_red: parse_hex_color("bright_red", &a.bright_red)?,
            bright_green: parse_hex_color("bright_green", &a.bright_green)?,
            bright_yellow: parse_hex_color("bright_yellow", &a.bright_yellow)?,
            bright_blue: parse_hex_color("bright_blue", &a.bright_blue)?,
            bright_magenta: parse_hex_color("bright_magenta", &a.bright_magenta)?,
            bright_cyan: parse_hex_color("bright_cyan", &a.bright_cyan)?,
            bright_white: parse_hex_color("bright_white", &a.bright_white)?,
        },
    })
}

/// Key for looking up provider colors: (theme_slug, provider_slug).
pub type ProviderColorsKey = (String, String);

/// Scan a themes directory and load all theme definitions and provider color files.
///
/// A `.toml` file is a ThemeDefinition if its stem contains no dots (e.g. `gruvbox-dark.toml`).
/// A `.toml` file is ProviderColors if its stem contains a dot (e.g. `gruvbox-dark.kitty.toml`).
///
/// Note: theme slugs must not contain dots — a file like `dr.doom.toml` would be
/// misparsed as provider colors for theme `dr` from provider `doom`.
pub fn load_themes_dir(
    dir: &Path,
) -> Result<(Vec<ThemeDefinition>, HashMap<ProviderColorsKey, ProviderColors>), ThemeError> {
    let mut definitions = Vec::new();
    let mut provider_colors: HashMap<ProviderColorsKey, ProviderColors> = HashMap::new();

    load_themes_dir_recursive(dir, &mut definitions, &mut provider_colors)?;

    Ok((definitions, provider_colors))
}

fn load_themes_dir_recursive(
    dir: &Path,
    definitions: &mut Vec<ThemeDefinition>,
    provider_colors: &mut HashMap<ProviderColorsKey, ProviderColors>,
) -> Result<(), ThemeError> {
    let entries = std::fs::read_dir(dir)?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            load_themes_dir_recursive(&path, definitions, provider_colors)?;
            continue;
        }

        let file_name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };

        if !file_name.ends_with(".toml") {
            continue;
        }

        // Strip the final .toml extension to get the stem
        let stem = &file_name[..file_name.len() - 5];

        // If the stem contains a dot, it's a provider colors file (e.g. "gruvbox-dark.kitty")
        // Otherwise it's a theme definition (e.g. "gruvbox-dark")
        if let Some(dot_pos) = stem.rfind('.') {
            let theme_slug = &stem[..dot_pos];
            let filename_provider = &stem[dot_pos + 1..];
            let content = std::fs::read_to_string(&path)?;
            let colors = parse_provider_colors(&content)?;
            if colors.provider != filename_provider {
                return Err(ThemeError::MissingField(format!(
                    "provider mismatch in {file_name}: filename says '{filename_provider}' but TOML says '{}'",
                    colors.provider
                )));
            }
            provider_colors.insert(
                (theme_slug.to_string(), colors.provider.clone()),
                colors,
            );
        } else {
            let content = std::fs::read_to_string(&path)?;
            let def = parse_theme_definition(&content, stem)?;
            definitions.push(def);
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    const DEFINITION_TOML: &str = r##"
name = "Gruvbox Dark"
variant = "dark"

[providers]
kitty = "Gruvbox Dark"
wezterm = "Gruvbox Dark (Gogh)"
"##;

    const PROVIDER_COLORS_TOML: &str = r##"
# AUTO-GENERATED by litmus extract-colors — do not edit
provider = "kitty"
source_version = "0.37.0"

[colors]
background = "#282828"
foreground = "#ebdbb2"
cursor = "#ebdbb2"
selection_background = "#ebdbb2"
selection_foreground = "#282828"

[colors.ansi]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"
"##;

    // -- Variant serde --

    #[test]
    fn variant_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&Variant::Dark).unwrap(), "\"dark\"");
        assert_eq!(serde_json::to_string(&Variant::Light).unwrap(), "\"light\"");
    }

    #[test]
    fn variant_deserializes_lowercase() {
        assert_eq!(
            serde_json::from_str::<Variant>("\"dark\"").unwrap(),
            Variant::Dark
        );
        assert_eq!(
            serde_json::from_str::<Variant>("\"light\"").unwrap(),
            Variant::Light
        );
    }

    // -- ThemeDefinition parsing --

    #[test]
    fn parse_theme_definition_basic() {
        let def = parse_theme_definition(DEFINITION_TOML, "gruvbox-dark").unwrap();
        assert_eq!(def.name, "Gruvbox Dark");
        assert_eq!(def.variant, Variant::Dark);
        assert_eq!(def.slug, "gruvbox-dark");
        assert_eq!(def.providers.len(), 2);
        assert_eq!(def.providers["kitty"], "Gruvbox Dark");
        assert_eq!(def.providers["wezterm"], "Gruvbox Dark (Gogh)");
    }

    #[test]
    fn parse_theme_definition_light_variant() {
        let toml = r#"
name = "One Light"
variant = "light"

[providers]
kitty = "One Light"
"#;
        let def = parse_theme_definition(toml, "one-light").unwrap();
        assert_eq!(def.variant, Variant::Light);
        assert_eq!(def.providers.len(), 1);
    }

    #[test]
    fn parse_theme_definition_empty_providers() {
        let toml = r#"
name = "Lonely Theme"
variant = "dark"

[providers]
"#;
        let def = parse_theme_definition(toml, "lonely").unwrap();
        assert!(def.providers.is_empty());
    }

    #[test]
    fn parse_theme_definition_invalid_toml() {
        assert!(parse_theme_definition("not valid toml :::", "bad").is_err());
    }

    #[test]
    fn parse_theme_definition_missing_variant() {
        let toml = r#"
name = "Missing Variant"

[providers]
kitty = "Test"
"#;
        assert!(parse_theme_definition(toml, "bad").is_err());
    }

    // -- ProviderColors parsing --

    #[test]
    fn parse_provider_colors_basic() {
        let pc = parse_provider_colors(PROVIDER_COLORS_TOML).unwrap();
        assert_eq!(pc.provider, "kitty");
        assert_eq!(pc.source_version, "0.37.0");
        assert_eq!(pc.background, Color::new(0x28, 0x28, 0x28));
        assert_eq!(pc.foreground, Color::new(0xeb, 0xdb, 0xb2));
        assert_eq!(pc.cursor, Color::new(0xeb, 0xdb, 0xb2));
        assert_eq!(pc.selection_background, Color::new(0xeb, 0xdb, 0xb2));
        assert_eq!(pc.selection_foreground, Color::new(0x28, 0x28, 0x28));
        assert_eq!(pc.ansi.black, Color::new(0x28, 0x28, 0x28));
        assert_eq!(pc.ansi.red, Color::new(0xcc, 0x24, 0x1d));
        assert_eq!(pc.ansi.bright_white, Color::new(0xeb, 0xdb, 0xb2));
    }

    #[test]
    fn parse_provider_colors_invalid_hex() {
        let bad = PROVIDER_COLORS_TOML.replace("#282828", "#ZZZZZZ");
        let err = parse_provider_colors(&bad).unwrap_err();
        match err {
            ThemeError::InvalidColor { field, value } => {
                assert_eq!(value, "#ZZZZZZ");
                // Could be background or black (both were #282828)
                assert!(field == "background" || field == "black");
            }
            _ => panic!("expected InvalidColor, got {err:?}"),
        }
    }

    #[test]
    fn parse_provider_colors_missing_field() {
        let bad = PROVIDER_COLORS_TOML.replace("source_version", "src_ver");
        assert!(parse_provider_colors(&bad).is_err());
    }

    // -- Directory loader --

    #[test]
    fn load_themes_dir_basic() {
        let dir = tempdir();
        let gruvbox = dir.join("gruvbox");
        fs::create_dir(&gruvbox).unwrap();

        fs::write(gruvbox.join("gruvbox-dark.toml"), DEFINITION_TOML).unwrap();
        fs::write(
            gruvbox.join("gruvbox-dark.kitty.toml"),
            PROVIDER_COLORS_TOML,
        )
        .unwrap();

        let (defs, colors) = load_themes_dir(&dir).unwrap();
        assert_eq!(defs.len(), 1);
        assert_eq!(defs[0].slug, "gruvbox-dark");
        assert_eq!(defs[0].name, "Gruvbox Dark");

        let key = ("gruvbox-dark".to_string(), "kitty".to_string());
        assert!(colors.contains_key(&key));
        assert_eq!(colors[&key].provider, "kitty");
    }

    #[test]
    fn load_themes_dir_flat_layout() {
        let dir = tempdir();
        fs::write(dir.join("tender.toml"), DEFINITION_TOML.replace("Gruvbox Dark", "Tender")).unwrap();
        fs::write(dir.join("tender.kitty.toml"), PROVIDER_COLORS_TOML).unwrap();

        let (defs, colors) = load_themes_dir(&dir).unwrap();
        assert_eq!(defs.len(), 1);
        assert_eq!(defs[0].slug, "tender");
        assert!(colors.contains_key(&("tender".to_string(), "kitty".to_string())));
    }

    #[test]
    fn load_themes_dir_multiple_providers() {
        let dir = tempdir();

        fs::write(dir.join("test.toml"), DEFINITION_TOML).unwrap();
        fs::write(dir.join("test.kitty.toml"), PROVIDER_COLORS_TOML).unwrap();

        let wezterm_toml = PROVIDER_COLORS_TOML.replace("kitty", "wezterm");
        fs::write(dir.join("test.wezterm.toml"), wezterm_toml).unwrap();

        let (defs, colors) = load_themes_dir(&dir).unwrap();
        assert_eq!(defs.len(), 1);
        assert!(colors.contains_key(&("test".to_string(), "kitty".to_string())));
        assert!(colors.contains_key(&("test".to_string(), "wezterm".to_string())));
    }

    #[test]
    fn load_themes_dir_empty() {
        let dir = tempdir();
        let (defs, colors) = load_themes_dir(&dir).unwrap();
        assert!(defs.is_empty());
        assert!(colors.is_empty());
    }

    #[test]
    fn load_themes_dir_ignores_non_toml() {
        let dir = tempdir();
        fs::write(dir.join("README.md"), "# Themes").unwrap();
        fs::write(dir.join("notes.txt"), "some notes").unwrap();
        let (defs, colors) = load_themes_dir(&dir).unwrap();
        assert!(defs.is_empty());
        assert!(colors.is_empty());
    }

    #[test]
    fn load_themes_dir_provider_mismatch() {
        let dir = tempdir();
        // Filename says wezterm but TOML content says kitty
        fs::write(dir.join("test.wezterm.toml"), PROVIDER_COLORS_TOML).unwrap();
        let err = load_themes_dir(&dir).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("provider mismatch"), "expected provider mismatch error, got: {msg}");
    }

    #[test]
    fn load_themes_dir_malformed_file() {
        let dir = tempdir();
        fs::write(dir.join("bad.toml"), "not valid toml :::").unwrap();
        assert!(load_themes_dir(&dir).is_err());
    }

    // -- from_theme + to_toml --

    #[test]
    fn from_theme_copies_all_fields() {
        let theme = crate::Theme {
            name: "Test".into(),
            background: Color::new(0x28, 0x28, 0x28),
            foreground: Color::new(0xeb, 0xdb, 0xb2),
            cursor: Color::new(0xeb, 0xdb, 0xb2),
            selection_background: Color::new(0xeb, 0xdb, 0xb2),
            selection_foreground: Color::new(0x28, 0x28, 0x28),
            ansi: crate::AnsiColors::from_array(std::array::from_fn(|i| {
                Color::new(i as u8 * 16, i as u8 * 16, i as u8 * 16)
            })),
        };
        let pc = ProviderColors::from_theme(&theme, "kitty", "0.37.0");
        assert_eq!(pc.provider, "kitty");
        assert_eq!(pc.source_version, "0.37.0");
        assert_eq!(pc.background, theme.background);
        assert_eq!(pc.foreground, theme.foreground);
        assert_eq!(pc.ansi, theme.ansi);
    }

    #[test]
    fn to_toml_round_trips_through_parse() {
        let pc = parse_provider_colors(PROVIDER_COLORS_TOML).unwrap();
        let toml_out = pc.to_toml();
        let pc2 = parse_provider_colors(&toml_out).unwrap();
        assert_eq!(pc, pc2);
    }

    fn tempdir() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("litmus-test-{}", std::process::id()));
        let unique = dir.join(format!("{}", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&unique).unwrap();
        unique
    }
}
