name = "Rosé Pine Moon"

[colors]
background = "#232136"
foreground = "#e0def4"
cursor = "#56526e"
selection_background = "#2a283e"
selection_foreground = "#e0def4"

[colors.ansi]
black = "#393552"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#3e8fb0"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"
bright_black = "#6e6a86"
bright_red = "#eb6f92"
bright_green = "#9ccfd8"
bright_yellow = "#f6c177"
bright_blue = "#3e8fb0"
bright_magenta = "#c4a7e7"
bright_cyan = "#ea9a97"
bright_white = "#e0def4"
