name = "Kanagawa"

[colors]
background = "#1f1f28"
foreground = "#dcd7ba"
cursor = "#c8c093"
selection_background = "#2d4f67"
selection_foreground = "#c8c093"

[colors.ansi]
black = "#16161d"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"
bright_black = "#727169"
bright_red = "#e82424"
bright_green = "#98bb6c"
bright_yellow = "#e6c384"
bright_blue = "#7fb4ca"
bright_magenta = "#938aa9"
bright_cyan = "#7aa89f"
bright_white = "#dcd7ba"
