name = "Flexoki Dark"

[colors]
background = "#100f0f"
foreground = "#cecdc3"
cursor = "#cecdc3"
selection_background = "#cecdc3"
selection_foreground = "#100f0f"

[colors.ansi]
black = "#100f0f"
red = "#d14d41"
green = "#879a39"
yellow = "#d0a215"
blue = "#4385be"
magenta = "#ce5d97"
cyan = "#3aa99f"
white = "#878580"
bright_black = "#575653"
bright_red = "#af3029"
bright_green = "#66800b"
bright_yellow = "#ad8301"
bright_blue = "#205ea6"
bright_magenta = "#a02f6f"
bright_cyan = "#24837b"
bright_white = "#cecdc3"
