[book]
title = "Litmus"
authors = []
language = "en"
src = "src"

[build]
build-dir = "dist"

[output.html]
fold.enable = true
fold.level = 0
additional-css = ["src/beans-sidebar.css"]

[preprocessor.beans]
command = "mdbook-beans"
